fragment UserFragment on User {
    id
    name
    nickname
    intro
    zaloId
    avatar
    isNew
    avatarFilePath
    nFollowing {
      id
      name
      nickname
      intro
      zaloId
      avatar
      isNew
      avatarFilePath
    }
    nFollower {
      id
      name
      nickname
      intro
      zaloId
      avatar
      isNew
      avatarFilePath
    }
}
