subscription onCreateComment($postId: Float!) {
  onCreateComment(postId: $postId) {
    id
    content
    createdAt
    creatorId
    creatorInfo {
      id
      name
      nickname
      createdAt
      avatarFilePath
    }
  }
}
