subscription onNewNotification($userId: Float!) {
  onNewNotification(userId: $userId) {
    id
    triggerId
    userId
    content
    link
    isSeen
    createdAt
    updatedAt
    triggerInfo {
      name
      avatarFilePath
    }
  }
}
