subscription onNewMessage($chatId: Float!) {
  onNewMessage(chatId: $chatId) {
    id
    sender
    chatId
    content
    media
    mediaType
    isRead
    createdAt
    senderInfo {
      id
      name
      nickname
      avatarFilePath
    }
  }
}
