subscription onReceiveMessage($userId: Float!) {
  onReceiveMessage(userId: $userId) {
    chatId
    userId
    message {
      id
      sender
      chatId
      content
      media
      mediaType
      senderInfo {
        id
        name
        avatarFilePath
      }
    }
  }
}
