subscription onUnLikePost($postId: Float!) {
  onUnLikePost(postId: $postId) {
    id
    postId
    userId
    createdAt
    creatorInfo {
      id
      name
      nickname
      avatarFilePath
    }
  }
}
