query getChats($page: Float!, $limit: Float!) {
  getChats(page: $page, limit: $limit) {
    items {
      id
      participants
      isTemp
      lastMessage
      createdAt
      unseenMessage
      participantInfo {
        id
        name
        nickname
        lastSeen
        avatarFilePath
        isBlockMe
      }
      lastMessageData {
        id
        content
        media
        mediaType
        sent
        received
        createdAt
        senderInfo {
          id
          name
          nickname
        }
      }
    }
    meta {
      itemCount
      totalItems
      itemsPerPage
      totalPages
      currentPage
    }
  }
}
