query getExistChat($participants: [Float!]!) {
  getExistChat(participants: $participants) {
    id
    participants
    isTemp
    lastMessage
    createdAt
    updatedAt
    participantInfo {
      id
      name
      nickname
      avatarFilePath
    }
  }
}
