query getExplorePost($page: Float!, $limit: Float!) {
  getExplorePost(page: $page, limit: $limit) {
    items {
      id
      mediasPath {
        filePath
      }
    }
    meta {
      itemCount
      totalItems
      itemsPerPage
      totalPages
      currentPage
    }
  }
}
