query getFollowingUser {
  getFollowingUser {
    id
    name
    nickname
    intro
    zaloId
    avatar
    isNew
    blocked
    lastSeen
    createdAt
    updatedAt
    avatarFilePath
    isRequestFollowMe
    isBlockMe
    followStatus
    nFollowing {
      id
      name
      nickname
      intro
      zaloId
      avatar
      isNew
      blocked
      lastSeen
      createdAt
      updatedAt
      avatarFilePath
      isRequestFollowMe
      isBlockMe
      followStatus
      nFollowing {
        id
        name
        nickname
        intro
        zaloId
        avatar
        isNew
        blocked
        lastSeen
        createdAt
        updatedAt
        avatarFilePath
        isRequestFollowMe
        isBlockMe
        followStatus
        nFollower {
          id
          name
          nickname
          intro
          zaloId
          avatar
          isNew
          blocked
          lastSeen
          createdAt
          updatedAt
          avatarFilePath
          isRequestFollowMe
          isBlockMe
          followStatus
          nFollowing {
            id
            name
            nickname
            intro
            zaloId
            avatar
            isNew
            blocked
            lastSeen
            createdAt
            updatedAt
            avatarFilePath
            isRequestFollowMe
            isBlockMe
            followStatus
          }
          nFollower {
            id
            name
            nickname
            intro
            zaloId
            avatar
            isNew
            blocked
            lastSeen
            createdAt
            updatedAt
            avatarFilePath
            isRequestFollowMe
            isBlockMe
            followStatus
          }
        }
      }
    }
    nFollower {
      id
      name
      nickname
      intro
      zaloId
      avatar
      isNew
      blocked
      lastSeen
      createdAt
      updatedAt
      avatarFilePath
      isRequestFollowMe
      isBlockMe
      followStatus
    }
  }
}
