query getNewFeed($limit: Int, $page: Int) {
  getNewFeed(limit: $limit, page: $page) {
    items {
      id
      caption
      rawCaption
      createdAt
      totalLike
      isLike
      mediasPath {
        filePath
      }
      creatorInfo {
        id
        name
        nickname
        avatarFilePath
      }
    }
    meta {
      itemCount
      totalItems
      itemsPerPage
      totalPages
      currentPage
    }
  }
}
