query getNewFeed($limit: Int, $page: Int) {
  getNewFeed(limit: $limit, page: $page) {
    items {
      id
      creatorId
      medias
      caption
      rawCaption
      createdAt
      updatedAt
      totalLike
      isLike
      mediasPath {
        filePath
      }
      creatorInfo {
        id
        name
        nickname
        intro
        zaloId
        avatar
        avatarFilePath
        followStatus
      }
    }
    meta {
      itemCount
      totalItems
      itemsPerPage
      totalPages
      currentPage
    }
  }
}
