query getNotification($page: Float!, $limit: Float!) {
  getNotification(page: $page, limit: $limit) {
    items {
      id
      triggerId
      userId
      content
      link
      isSeen
      createdAt
      updatedAt
      triggerInfo {
        id
        name
        nickname
        avatarFilePath
        isBlockMe
      }
    }
    meta {
      itemCount
      totalItems
      itemsPerPage
      totalPages
      currentPage
    }
  }
}
