query getPostDetail($id: Float!) {
  getPostDetail(id: $id) {
    id
    caption
    rawCaption
    createdAt
    updatedAt
    totalLike
    isLike
    mediasPath {
      filePath
    }
    creatorInfo {
      id
      name
      nickname
      avatarFilePath
      isBlockMe
    }
  }
}
