query getPostComment($page: Float!, $limit: Float!, $postId: Float!) {
  getPostComment(page: $page, limit: $limit, postId: $postId) {
    items {
      id
      content
      createdAt
      creatorId
      creatorInfo {
        id
        name
        nickname
        avatarFilePath
      }
    }
    meta {
      itemCount
      totalItems
      itemsPerPage
      totalPages
      currentPage
    }
  }
}
