query getPostDetail($id: Float!) {
  getPostDetail(id: $id) {
    id
    creatorId
    medias
    caption
    rawCaption
    createdAt
    updatedAt
    postComments {
      id
      creatorId
      postId
      parentId
      content
      createdAt
      creatorInfo {
        name
        nickname
        avatarFilePath
      }
    }
    totalLike
    isLike
    mediasPath {
      filePath
    }
    creatorInfo {
      id
      name
      nickname
      intro
      zaloId
      avatar
      isNew
      createdAt
      updatedAt
      avatarFilePath
      followStatus
    }
  }
}
