query getStreams {
  getStreams {
    id
    streamerId
    streamUrl
    viewUrl
    status
    previewUrl
    muxStreamId
    muxPlaybackId
    createdAt
    updatedAt
    streamerInfo {
      id
      name
      avatarFilePath
    }
  }
}
