query getUserInfo($id: Float!) {
  getUserInfo(id: $id) {
    id
    name
    nickname
    intro
    avatar
    isNew
    createdAt
    isRequestFollowMe
    avatarFilePath
    followStatus
    isBlockMe
    nFollowing {
      id
      name
      nickname
      avatarFilePath
    }
    nFollower {
      id
      name
      nickname
      avatarFilePath
    }
  }
}
