query getUserPost($page: Float!, $limit: Float!, $userId: Float!) {
  getUserPost(page: $page, limit: $limit, userId: $userId) {
    items {
      id
      mediasPath {
        filePath
      }
    }
    meta {
      itemCount
      totalItems
      itemsPerPage
      totalPages
      currentPage
    }
  }
}
