query me {
  me {
    id
    name
    nickname
    intro
    zaloId
    avatar
    isNew
    createdAt
    updatedAt
    avatarFilePath
    followStatus
    nFollowing {
      id
      name
      nickname
      intro
      zaloId
      avatar
      isNew
      createdAt
      updatedAt
      avatarFilePath
      followStatus
    }
    nFollower {
      id
      name
      nickname
      intro
      zaloId
      avatar
      isNew
      createdAt
      updatedAt
      avatarFilePath
      followStatus
    }
  }
}
