query searchUser($page: Float!, $limit: Float!, $isRestricted: Boolean, $keyword: String!) {
  searchUser(page: $page, limit: $limit, isRestricted: $isRestricted, keyword: $keyword) {
    items {
      id 
      name
      nickname
      avatarFilePath
    }
    meta {
      itemCount
      totalItems
      itemsPerPage
      totalPages
      currentPage
    }
  }
}
